'use client'

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#f7fafa', fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
      <div style={{ maxWidth: '700px', margin: '0 auto', padding: '40px 24px 80px' }}>
        <a href="/" style={{ fontFamily: "'Nunito', sans-serif", fontSize: '20px', fontWeight: 900, color: '#0d2b28', textDecoration: 'none' }}>
          learni<span style={{ color: '#2ec4b6' }}>.</span>
        </a>

        <h1 style={{ fontFamily: "'Nunito', sans-serif", fontSize: '32px', fontWeight: 900, color: '#0d2b28', marginTop: '32px', marginBottom: '8px' }}>
          Privacy Policy
        </h1>
        <p style={{ color: '#5a8a84', fontSize: '14px', marginBottom: '32px' }}>Last updated: 15 April 2026</p>

        <div style={{ fontSize: '15px', lineHeight: 1.8, color: '#2d3a38' }}>
          <h2 style={h2Style}>1. Who We Are</h2>
          <p>Learni is operated by Momentum Ventures Limited, based in Auckland, New Zealand. We comply with the New Zealand Privacy Act 2020.</p>
          <p>Questions? <a href="https://learniapp.co/#chat" style={{ color: '#2ec4b6' }}>Chat with us</a> or email <a href="mailto:hello@learniapp.co" style={{ color: '#2ec4b6' }}>hello@learniapp.co</a></p>

          <h2 style={h2Style}>2. Information We Collect</h2>

          <h3 style={h3Style}>Parent account information</h3>
          <ul style={ulStyle}>
            <li>Email address</li>
            <li>Full name</li>
            <li>Password (encrypted — we cannot see it)</li>
            <li>Payment information (processed by our payment provider — we never see or store full card details)</li>
          </ul>

          <h3 style={h3Style}>Child profile information</h3>
          <ul style={ulStyle}>
            <li>First name</li>
            <li>Age and school year level</li>
            <li>PIN (for child login)</li>
            <li>Username (chosen by the child)</li>
            <li>Avatar preferences</li>
            <li>Preferred language</li>
          </ul>

          <h3 style={h3Style}>Learning data</h3>
          <ul style={ulStyle}>
            <li>Session history (questions, answers, time spent)</li>
            <li>Topic mastery scores</li>
            <li>Stars earned and jar allocations</li>
            <li>Baseline assessment results</li>
          </ul>

          <h3 style={h3Style}>Technical data</h3>
          <ul style={ulStyle}>
            <li>Browser type and device information</li>
            <li>IP address</li>
            <li>Pages visited and feature usage</li>
          </ul>

          <h2 style={h2Style}>3. What We Do NOT Collect</h2>
          <ul style={ulStyle}>
            <li>We do not collect children&apos;s email addresses</li>
            <li>We do not record or store children&apos;s voice data (speech recognition runs in your browser only)</li>
            <li>We do not use cookies for advertising or tracking</li>
            <li>We do not sell any data to third parties. Ever.</li>
          </ul>

          <h2 style={h2Style}>4. How We Use Your Information</h2>
          <ul style={ulStyle}>
            <li>To provide and personalise the Learni tutoring service</li>
            <li>To generate Earni&apos;s spoken responses (tutoring content only — no personal data is included)</li>
            <li>To send parent summary emails and account notifications</li>
            <li>To process subscription payments securely</li>
            <li>To improve our service and fix issues</li>
          </ul>

          <h2 style={h2Style}>5. Third-Party Service Providers</h2>
          <p>To operate Learni, we work with carefully selected third-party service providers. These include providers for:</p>
          <ul style={ulStyle}>
            <li><strong>Database and infrastructure</strong> — your data is stored securely in Australia</li>
            <li><strong>Website hosting</strong> — served via a global content delivery network</li>
            <li><strong>AI tutoring content</strong> — session content is generated by a leading AI provider; no personal data is retained by the provider after processing</li>
            <li><strong>Voice synthesis</strong> — Earni&apos;s voice is generated using tutoring content only; no personal data is included</li>
            <li><strong>Payment processing</strong> — handled by a PCI-DSS compliant payment provider; we never store card details</li>
            <li><strong>Email delivery</strong> — used to send parent summaries and account notifications</li>
          </ul>
          <p>All providers are bound by data processing agreements and are only permitted to use your data to provide their service to us. A full list of our data processors is available on request — chat with us or email <a href="mailto:hello@learniapp.co" style={{ color: '#2ec4b6' }}>hello@learniapp.co</a>.</p>

          <h2 style={h2Style}>6. Data Sharing</h2>
          <p>We share your data only with:</p>
          <ul style={ulStyle}>
            <li><strong>Service providers</strong> — only what is necessary for them to provide their service</li>
            <li><strong>Law enforcement</strong> — if required by law</li>
          </ul>
          <p>We never sell your data. We never share it for advertising purposes.</p>

          <h2 style={h2Style}>7. Children&apos;s Privacy</h2>
          <p>We take children&apos;s privacy seriously. Child profiles are created and managed by parents. We collect only the minimum information needed to provide the tutoring service. Children do not have email addresses on our system. Parents can view, edit, or delete their child&apos;s data at any time from the parent Hub.</p>

          <h2 style={h2Style}>8. Data Retention</h2>
          <ul style={ulStyle}>
            <li>Active accounts: data retained while your subscription is active</li>
            <li>Cancelled accounts: data deleted within 90 days of cancellation</li>
            <li>You can request immediate deletion at any time</li>
          </ul>

          <h2 style={h2Style}>9. Your Rights</h2>
          <p>Under the New Zealand Privacy Act 2020, you have the right to:</p>
          <ul style={ulStyle}>
            <li>Access the personal information we hold about you</li>
            <li>Correct any inaccurate information</li>
            <li>Request deletion of your data</li>
            <li>Ask what data processors we use</li>
          </ul>
          <p>To exercise any of these rights, <a href="https://learniapp.co/#chat" style={{ color: '#2ec4b6' }}>chat with us</a> or email <a href="mailto:hello@learniapp.co" style={{ color: '#2ec4b6' }}>hello@learniapp.co</a>.</p>

          <h2 style={h2Style}>10. Security</h2>
          <ul style={ulStyle}>
            <li>All data is encrypted in transit (HTTPS/TLS)</li>
            <li>Database access uses row-level security — accounts cannot access each other&apos;s data</li>
            <li>Passwords are hashed and never stored in plain text</li>
            <li>Payment processing is fully handled by our PCI-DSS compliant payment provider</li>
          </ul>

          <h2 style={h2Style}>11. Cookies</h2>
          <p>We use only essential cookies required for the service to function (e.g. keeping you logged in). We do not use advertising or tracking cookies. You can clear cookies at any time via your browser settings.</p>

          <h2 style={h2Style}>12. Changes to This Policy</h2>
          <p>We may update this policy from time to time. We&apos;ll notify you by email if we make material changes. The date at the top of this page reflects the most recent update.</p>

          <h2 style={h2Style}>13. Contact</h2>
          <p>Questions about this policy? Email us at <a href="mailto:hello@learniapp.co" style={{ color: '#2ec4b6' }}>hello@learniapp.co</a>.</p>
          <p style={{ marginTop: '8px' }}>Momentum Ventures Limited, Auckland, New Zealand.</p>
        </div>
      </div>
    </div>
  )
}

const h2Style: React.CSSProperties = {
  fontFamily: "'Nunito', sans-serif",
  fontSize: '20px',
  fontWeight: 800,
  color: '#0d2b28',
  marginTop: '36px',
  marginBottom: '8px',
}

const h3Style: React.CSSProperties = {
  fontFamily: "'Nunito', sans-serif",
  fontSize: '16px',
  fontWeight: 700,
  color: '#0d2b28',
  marginTop: '20px',
  marginBottom: '4px',
}

const ulStyle: React.CSSProperties = {
  paddingLeft: '20px',
  marginTop: '8px',
  marginBottom: '12px',
}
